[0m07:13:13.417558 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10617e720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cd37d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cd3470>]}


============================== 07:13:13.420876 | 77173176-1767-4f95-90ef-38d5d2003009 ==============================
[0m07:13:13.420876 [info ] [MainThread]: Running with dbt=1.9.4
[0m07:13:13.421195 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/sumitkamra/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init dbt', 'send_anonymous_usage_stats': 'True'}
[0m07:17:07.151020 [debug] [MainThread]: Starter project path: /Users/sumitkamra/.pyenv/versions/3.12.9/envs/foundryAI_global/lib/python3.12/site-packages/dbt/include/starter_project
[0m07:17:07.164221 [info ] [MainThread]: 
Your new dbt project "dbt_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m07:17:07.164709 [info ] [MainThread]: Setting up your profile.
[0m07:38:07.733352 [info ] [MainThread]: Profile dbt_pipeline written to /Users/sumitkamra/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m07:38:07.757782 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 1494.3927, "process_in_blocks": "0", "process_kernel_time": 0.28013, "process_mem_max_rss": "177176576", "process_out_blocks": "0", "process_user_time": 1.004967}
[0m07:38:07.760829 [debug] [MainThread]: Command `dbt init` succeeded at 07:38:07.760630 after 1494.40 seconds
[0m07:38:07.761789 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10617fe00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077ca720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d024e0>]}
[0m07:38:07.762497 [debug] [MainThread]: Flushing usage events
[0m07:38:09.510660 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:43:24.408997 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1069a12b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106adcf80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106adcc80>]}


============================== 10:43:24.412490 | 6905c7fd-14bf-4f64-bddc-ec2532fc64df ==============================
[0m10:43:24.412490 [info ] [MainThread]: Running with dbt=1.9.4
[0m10:43:24.412829 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/sumitkamra/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:43:24.413123 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sumitkamra/code/sumitkamra20/foundryai/capstone/marketing-insight-pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:43:24.414481 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.043623667, "process_in_blocks": "0", "process_kernel_time": 0.113294, "process_mem_max_rss": "101580800", "process_out_blocks": "0", "process_user_time": 0.702022}
[0m10:43:24.414750 [debug] [MainThread]: Command `dbt test` failed at 10:43:24.414694 after 0.04 seconds
[0m10:43:24.414937 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067a86e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106adcd10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106aded20>]}
[0m10:43:24.415107 [debug] [MainThread]: Flushing usage events
[0m10:43:25.584651 [debug] [MainThread]: An error was encountered while trying to flush usage events
